# Generated by Django 5.0.4 on 2024-05-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentariosAdicionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DatosDemograficos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_temporal', models.DateTimeField(auto_now_add=True)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('genero', models.CharField(max_length=50)),
                ('area_empresa', models.CharField(max_length=100)),
                ('antiguedad_empresa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbierta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacion_1', models.CharField(default='', max_length=200)),
                ('situacion_2', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaCompaneros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiesta_integracion', models.CharField(max_length=200)),
                ('defensa_intereses', models.CharField(max_length=200)),
                ('representante_directivas', models.CharField(max_length=200)),
                ('organizador_equipo_deportivo', models.CharField(max_length=200)),
                ('organizador_equipos_trabajo', models.CharField(max_length=200)),
                ('divulgacion_hechos', models.CharField(max_length=200)),
                ('confianza_secreto', models.CharField(max_length=200)),
                ('resolver_problemas', models.CharField(max_length=200)),
                ('enseñanza_trabajo', models.CharField(max_length=200)),
                ('lider_funcionario', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaDefectos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defecto_1', models.CharField(max_length=200)),
                ('defecto_2', models.CharField(max_length=200)),
                ('defecto_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaDefectosPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defectos_persona_A', models.CharField(max_length=200)),
                ('defectos_persona_B', models.CharField(max_length=200)),
                ('defectos_persona_C', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaHabitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habito_1', models.CharField(max_length=200)),
                ('habito_2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaHabitosAnuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habito_1', models.CharField(max_length=200)),
                ('habito_2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaHabitosMensuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habito_1', models.CharField(max_length=200)),
                ('habito_2', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaVirtudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtud_1', models.CharField(max_length=200)),
                ('virtud_2', models.CharField(max_length=200)),
                ('virtud_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaAbiertaVirtudesPersonas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtudes_persona_A', models.CharField(max_length=200)),
                ('virtudes_persona_B', models.CharField(max_length=200)),
                ('virtudes_persona_C', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaImportancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_43_opcion_1', models.IntegerField(default=0)),
                ('pregunta_43_opcion_2', models.IntegerField(default=0)),
                ('pregunta_43_opcion_3', models.IntegerField(default=0)),
                ('pregunta_44_opcion_1', models.IntegerField(default=0)),
                ('pregunta_44_opcion_2', models.IntegerField(default=0)),
                ('pregunta_44_opcion_3', models.IntegerField(default=0)),
                ('pregunta_44_opcion_4', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_62_opcion_1', models.CharField(max_length=200)),
                ('pregunta_62_opcion_2', models.CharField(max_length=200)),
                ('pregunta_62_opcion_3', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntasCerradas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta_1', models.CharField(max_length=200)),
                ('pregunta_2', models.CharField(max_length=200)),
                ('pregunta_3', models.CharField(max_length=200)),
                ('pregunta_4', models.CharField(max_length=200)),
                ('pregunta_5', models.CharField(max_length=200)),
                ('pregunta_6', models.CharField(max_length=200)),
                ('pregunta_7', models.CharField(max_length=200)),
                ('pregunta_8', models.CharField(max_length=200)),
                ('pregunta_9', models.CharField(max_length=200)),
                ('pregunta_10', models.CharField(max_length=200)),
                ('pregunta_11', models.CharField(max_length=200)),
                ('pregunta_12', models.CharField(max_length=200)),
                ('pregunta_13', models.CharField(max_length=200)),
                ('pregunta_14', models.CharField(max_length=200)),
                ('pregunta_15', models.CharField(max_length=200)),
                ('pregunta_16', models.CharField(max_length=200)),
                ('pregunta_17', models.CharField(max_length=200)),
                ('pregunta_18', models.CharField(max_length=200)),
                ('pregunta_19', models.CharField(max_length=200)),
                ('pregunta_20', models.CharField(max_length=200)),
                ('pregunta_21', models.CharField(max_length=200)),
                ('pregunta_22', models.CharField(max_length=200)),
                ('pregunta_23', models.CharField(max_length=200)),
                ('pregunta_24', models.CharField(max_length=200)),
                ('pregunta_25', models.CharField(max_length=200)),
                ('pregunta_26', models.CharField(max_length=200)),
                ('pregunta_27', models.CharField(max_length=200)),
                ('pregunta_28', models.CharField(max_length=200)),
                ('pregunta_29', models.CharField(max_length=200)),
                ('pregunta_30', models.CharField(max_length=200)),
                ('pregunta_31', models.CharField(max_length=200)),
                ('pregunta_32', models.CharField(max_length=200)),
                ('pregunta_33', models.CharField(max_length=200)),
                ('pregunta_34', models.CharField(max_length=200)),
                ('pregunta_35', models.CharField(max_length=200)),
                ('pregunta_36', models.CharField(max_length=200)),
                ('pregunta_37', models.CharField(max_length=200)),
                ('pregunta_38', models.CharField(max_length=200)),
                ('pregunta_39', models.CharField(max_length=200)),
                ('pregunta_40', models.CharField(max_length=200)),
                ('pregunta_41', models.CharField(max_length=200)),
            ],
        ),
    ]
