# Generated by Django 5.0.4 on 2024-05-03 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cicloapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preguntaabierta',
            name='situacion_1',
        ),
        migrations.RemoveField(
            model_name='preguntaabierta',
            name='situacion_2',
        ),
        migrations.AddField(
            model_name='preguntaabierta',
            name='pregunta_42_situacion_1',
            field=models.CharField(default='default_value', max_length=200),
        ),
        migrations.AddField(
            model_name='preguntaabierta',
            name='pregunta_42_situacion_2',
            field=models.CharField(default='default_value', max_length=200),
        ),
    ]
